/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/beetleAnimated.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.idleanimations.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[0.06, 0, 0]}>
        <primitive object={nodes.root} />
        <primitive object={nodes.IKtargetL} />
        <primitive object={nodes.arm1upL005} />
        <primitive object={nodes.IKtarget2L} />
        <primitive object={nodes.IKpole2L} />
        <primitive object={nodes.IKtarget3L} />
        <primitive object={nodes.IKTarget3L} />
        <primitive object={nodes.IKTargetM} />
        <primitive object={nodes.IKtargetR} />
        <primitive object={nodes.arm1upR005} />
        <primitive object={nodes.IKtarget2R} />
        <primitive object={nodes.IKpole2R} />
        <primitive object={nodes.IKtarget3R} />
        <primitive object={nodes.IKTarget3R} />
        <skinnedMesh castShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Material}
          skeleton={nodes.Cube002.skeleton}
        />
        <skinnedMesh castShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.001']}
          skeleton={nodes.Cube002_1.skeleton}
        />
        <skinnedMesh castShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['Material.002']}
          skeleton={nodes.Cube002_2.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/beetleAnimated.glb')
